!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0.5 #total score to pass
    t: 750
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: -1, y: -1, z: -1}
      rotations: [-1]
    - !Item
      name: GoodGoalMultiBounce
      positions:
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      rotations: [-1,-1,-1,-1,-1,-1]
      sizes:
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
    - !Item
      name: GoodGoalBounce
      positions:
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      rotations: [-1,-1,-1,-1]
      sizes:
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
    - !Item
      name: BadGoalBounce
      positions:
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
 # No rotations specified - will be randomised
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
 # No rotations, sizes, or colors specified - will be randomised
    blackouts: [-15]
