!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0.5 #total score to pass
    t: 750
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 2, z: -1} #Agent Position
      rotations: [-1]
    - !Item
      name: GoodGoalBounce
      positions:
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      rotations: [-1,-1,-1,-1,-1,-1,-1]
      sizes:
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
    - !Item
      name: BadGoalBounce
      positions:
      - !Vector3 {x: -1, y: 5, z: -1}
      rotations: [-1]
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 20, y: 0, z: 20} # Platform Position
      rotations: [0] # Platform Rotation
      sizes:
      - !Vector3 {x: 3, y: 2, z: 40} # Platform Size
      colors:
      - !RGB {r: 0, g: 0, b: 256} #Platform Color
    - !Item
      name: Ramp
      positions:
      - !Vector3 {x: 14.5, y: 0, z: 20} # Ramp Position
      rotations: [270] # Ramp Rotation
      sizes:
      - !Vector3 {x: 40, y: 2, z: 8} # Ramp Size
      colors:
      - !RGB {r: 256, g: 0, b: 256} #Ramp Color
